services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:5672"
      - "25672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_payment
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - ./logs/order-api:/app/order-api/logs
      - ./logs/order-consumer:/app/order-consumer/logs
      - ./logs/payment-consumer:/app/payment-consumer/logs
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  order-api:
    image: rabbitmq-order-payment-order-api:1.0.0
    depends_on:
      - rabbitmq
      - mysql
      - redis
    ports:
      - "18080:8080"
      - "19080:9000"
    volumes:
      - ./logs/order-api:/app/order-api/logs
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_payment?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_JPA_OPEN_IN_VIEW: false
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      MANAGEMENT_SERVER_PORT: 9000

  order-consumer:
    image: rabbitmq-order-payment-order-consumer:1.0.0
    depends_on:
      - rabbitmq
      - mysql
      - redis
    ports:
      - "18081:8080"
      - "19081:9001"
    volumes:
      - ./logs/order-consumer:/app/order-consumer/logs
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_payment?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_JPA_OPEN_IN_VIEW: false
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      MANAGEMENT_SERVER_PORT: 9001

  payment-consumer:
    image: rabbitmq-order-payment-payment-consumer:1.0.0
    depends_on:
      - rabbitmq
      - mysql
      - redis
    ports:
      - "18082:8080"
      - "19082:9002"
    volumes:
      - ./logs/payment-consumer:/app/payment-consumer/logs
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      MANAGEMENT_SERVER_PORT: 9002
