server:
  port: 8082

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:15672}
    username: guest
    password: guest
    publisher-returns: true

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9002}
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: payment-consumer