server:
  port: 8081

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:mysql://localhost:13306/order_payment?serverTimezone=Asia/Seoul&useSSL=false
    username: mysqluser
    password: mysqlpw

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # ??? Entity? ???? create? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jdbc:
      repositories:
        enabled: false
    redis:
      host: localhost
      port: 16379
      repositories:
        enabled: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:15672}
    username: guest
    password: guest
    publisher-returns: true

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9001}
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: order-consumer